[package]
name = "actix-svelte"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
mime_guess = "2.0.5"
rust-embed = { version = "8.5.0", features = ["actix", "actix-web"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
