CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY NOT NULL,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

    -- last_login TIMESTAMP DEFAULT NULL,
    -- is_active BOOLEAN NOT NULL DEFAULT TRUE,
    -- is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    -- email TEXT NOT NULL UNIQUE